/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import market.femi.api.models.ApiAction
import market.femi.api.models.ApiAiModel
import market.femi.api.models.ApiChatMessage
import market.femi.api.models.ApiPay
import market.femi.api.models.ApiStatus

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * default values
 *
 * @param action 
 * @param audio input audio as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side
 * @param balance 
 * @param credit 
 * @param file filename of result to retrieve
 * @param id uuid v7
 * @param image input image as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side
 * @param messages default value is non-empty array
 * @param model 
 * @param pay 
 * @param prompt 
 * @param requestId transient, managed by server
 * @param status 
 * @param userId 
 */
@Serializable

data class API (

    @SerialName(value = "action") @Required val action: ApiAction,

    /* input audio as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side */
    @SerialName(value = "audio") @Required val audio: kotlin.String,

    @SerialName(value = "balance") @Required val balance: kotlin.Long,

    @SerialName(value = "credit") @Required val credit: kotlin.Long,

    /* filename of result to retrieve */
    @SerialName(value = "file") @Required val file: kotlin.String,

    /* uuid v7 */
    @SerialName(value = "id") @Required val id: kotlin.uuid.Uuid,

    /* input image as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side */
    @SerialName(value = "image") @Required val image: kotlin.String,

    /* default value is non-empty array */
    @SerialName(value = "messages") @Required val messages: kotlin.collections.List<ApiChatMessage>,

    @SerialName(value = "model") @Required val model: ApiAiModel,

    @SerialName(value = "pay") @Required val pay: ApiPay,

    @SerialName(value = "prompt") @Required val prompt: kotlin.String,

    /* transient, managed by server */
    @SerialName(value = "request_id") @Required val requestId: kotlin.String,

    @SerialName(value = "status") @Required val status: ApiStatus,

    @SerialName(value = "user_id") @Required val userId: kotlin.String

) {


}

