/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * Values: ZImageTurbo,NanoBanana2,Flux2Pro,Ltx2_3A2V,NgrokText
 */
@Serializable
enum class ApiAiModel(val value: kotlin.String) {

    @SerialName(value = "ZImageTurbo")
    ZImageTurbo("ZImageTurbo"),

    @SerialName(value = "NanoBanana2")
    NanoBanana2("NanoBanana2"),

    @SerialName(value = "Flux2Pro")
    Flux2Pro("Flux2Pro"),

    @SerialName(value = "Ltx2_3A2V")
    Ltx2_3A2V("Ltx2_3A2V"),

    @SerialName(value = "NgrokText")
    NgrokText("NgrokText");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ApiAiModel) "$data" else null

        /**
         * Returns a valid [ApiAiModel] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ApiAiModel? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

