/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import market.femi.api.models.ApiPayProvider

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * default values
 *
 * @param currency 
 * @param id uuid v7
 * @param jws Signed transaction JWS from StoreKit; the input to Apple verification.
 * @param loaded 
 * @param packageName 
 * @param price 
 * @param productId 
 * @param provider Selects the verification path: Apple App Store vs Google Play.
 * @param refId Globally-unique purchase id, used as the idempotency key for both stores. Apple: the `transactionId`, extracted server-side from the verified JWS   (empty on the incoming request — the server fills it in). Google: the `purchaseToken`, sent by the client. It is both the input to   Play Developer API verification and the idempotency key.
 * @param userId 
 * @param orderId Google's per-purchase `orderId`, returned by the Play Developer API (not the client). Not used for dedup — `ref_id` is — because promo-code purchases may have no `orderId`.
 */
@Serializable

data class ApiPay (

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    /* uuid v7 */
    @SerialName(value = "id") @Required val id: kotlin.uuid.Uuid,

    /* Signed transaction JWS from StoreKit; the input to Apple verification. */
    @SerialName(value = "jws") @Required val jws: kotlin.String,

    @SerialName(value = "loaded") @Required val loaded: kotlin.Boolean,

    @SerialName(value = "package_name") @Required val packageName: kotlin.String,

    @SerialName(value = "price") @Required val price: kotlin.Long,

    @SerialName(value = "product_id") @Required val productId: kotlin.String,

    /* Selects the verification path: Apple App Store vs Google Play. */
    @SerialName(value = "provider") @Required val provider: ApiPayProvider,

    /* Globally-unique purchase id, used as the idempotency key for both stores. Apple: the `transactionId`, extracted server-side from the verified JWS   (empty on the incoming request — the server fills it in). Google: the `purchaseToken`, sent by the client. It is both the input to   Play Developer API verification and the idempotency key. */
    @SerialName(value = "ref_id") @Required val refId: kotlin.String,

    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    /* Google's per-purchase `orderId`, returned by the Play Developer API (not the client). Not used for dedup — `ref_id` is — because promo-code purchases may have no `orderId`. */
    @SerialName(value = "order_id") val orderId: kotlin.String? = null

) {


}

