/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param artist 
 * @param audio 
 * @param chat 
 * @param creator 
 * @param director 
 * @param falFlux2Pro 
 * @param falNanoBanana2 
 * @param falZImageTurbo 
 * @param gb 
 * @param generate 
 * @param id 
 * @param image 
 * @param lyricSync 
 * @param microPixLyra 
 * @param microPixVega 
 * @param nanoPixLuna 
 * @param nanoRenSpica 
 * @param question 
 * @param summary 
 * @param upload 
 */
@Serializable

data class ApiPricing (

    @SerialName(value = "artist") @Required val artist: kotlin.Long,

    @SerialName(value = "audio") @Required val audio: kotlin.Long,

    @SerialName(value = "chat") @Required val chat: kotlin.Long,

    @SerialName(value = "creator") @Required val creator: kotlin.Long,

    @SerialName(value = "director") @Required val director: kotlin.Long,

    @SerialName(value = "fal_flux2_pro") @Required val falFlux2Pro: kotlin.Long,

    @SerialName(value = "fal_nano_banana2") @Required val falNanoBanana2: kotlin.Long,

    @SerialName(value = "fal_z_image_turbo") @Required val falZImageTurbo: kotlin.Long,

    @SerialName(value = "gb") @Required val gb: kotlin.Long,

    @SerialName(value = "generate") @Required val generate: kotlin.Long,

    @SerialName(value = "id") @Required val id: kotlin.uuid.Uuid,

    @SerialName(value = "image") @Required val image: kotlin.Long,

    @SerialName(value = "lyric_sync") @Required val lyricSync: kotlin.Long,

    @SerialName(value = "micro_pix_lyra") @Required val microPixLyra: kotlin.Long,

    @SerialName(value = "micro_pix_vega") @Required val microPixVega: kotlin.Long,

    @SerialName(value = "nano_pix_luna") @Required val nanoPixLuna: kotlin.Long,

    @SerialName(value = "nano_ren_spica") @Required val nanoRenSpica: kotlin.Long,

    @SerialName(value = "question") @Required val question: kotlin.Long,

    @SerialName(value = "summary") @Required val summary: kotlin.Long,

    @SerialName(value = "upload") @Required val upload: kotlin.Long

) {


}

