/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import market.femi.api.models.ApplePayStatus

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Put default values
 *
 * @param credit 
 * @param currency 
 * @param id uuid v7
 * @param jws 
 * @param loaded 
 * @param price 
 * @param productId 
 * @param status 
 * @param transactionId 
 * @param userId 
 */
@Serializable

data class ApplePay (

    @SerialName(value = "credit") @Required val credit: kotlin.Long,

    @SerialName(value = "currency") @Required val currency: kotlin.String,

    /* uuid v7 */
    @SerialName(value = "id") @Required val id: kotlin.uuid.Uuid,

    @SerialName(value = "jws") @Required val jws: kotlin.String,

    @SerialName(value = "loaded") @Required val loaded: kotlin.Boolean,

    @SerialName(value = "price") @Required val price: kotlin.Long,

    @SerialName(value = "product_id") @Required val productId: kotlin.String,

    @SerialName(value = "status") @Required val status: ApplePayStatus,

    @SerialName(value = "transaction_id") @Required val transactionId: kotlin.String,

    @SerialName(value = "user_id") @Required val userId: kotlin.String

) {


}

