/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param context 
 * @param goal 
 * @param id 
 * @param line 
 * @param startTime 
 */
@Serializable

data class AudioLine (

    @SerialName(value = "context") @Required val context: kotlin.String,

    @SerialName(value = "goal") @Required val goal: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.uuid.Uuid,

    @SerialName(value = "line") @Required val line: kotlin.String,

    @SerialName(value = "start_time") @Required val startTime: kotlin.Double

) {


}

