/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param description 
 * @param type 
 */
@Serializable

data class Charge (

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "type") @Required val type: Charge.Type

) {

    /**
     * 
     *
     * Values: Charge
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Charge") Charge("Charge");
    }

}

