/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param falRequestId 
 * @param file base64 return
 * @param prompt 
 * @param type 
 */
@Serializable

data class Flux2Pro (

    @SerialName(value = "fal_request_id") @Required val falRequestId: kotlin.String,

    /* base64 return */
    @SerialName(value = "file") @Required val file: kotlin.String,

    @SerialName(value = "prompt") @Required val prompt: kotlin.String,

    @SerialName(value = "type") @Required val type: Flux2Pro.Type

) {

    /**
     * 
     *
     * Values: Flux2Pro
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Flux2Pro") Flux2Pro("Flux2Pro");
    }

}

