/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param credit 
 * @param loaded 
 * @param packageName 
 * @param productId 
 * @param purchaseToken 
 * @param type 
 * @param orderId 
 */
@Serializable

data class GooglePay (

    @SerialName(value = "credit") @Required val credit: kotlin.Long,

    @SerialName(value = "loaded") @Required val loaded: kotlin.Boolean,

    @SerialName(value = "package_name") @Required val packageName: kotlin.String,

    @SerialName(value = "product_id") @Required val productId: kotlin.String,

    @SerialName(value = "purchase_token") @Required val purchaseToken: kotlin.String,

    @SerialName(value = "type") @Required val type: GooglePay.Type,

    @SerialName(value = "order_id") val orderId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: GooglePay
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "GooglePay") GooglePay("GooglePay");
    }

}

