/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param audio input audio as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side
 * @param comfyRequestId 
 * @param file base64 return
 * @param image input image as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side
 * @param prompt 
 * @param type 
 */
@Serializable

data class Ltx23A2V (

    /* input audio as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side */
    @SerialName(value = "audio") @Required val audio: kotlin.String,

    @SerialName(value = "comfy_request_id") @Required val comfyRequestId: kotlin.String,

    /* base64 return */
    @SerialName(value = "file") @Required val file: kotlin.String,

    /* input image as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side */
    @SerialName(value = "image") @Required val image: kotlin.String,

    @SerialName(value = "prompt") @Required val prompt: kotlin.String,

    @SerialName(value = "type") @Required val type: Ltx23A2V.Type

) {

    /**
     * 
     *
     * Values: Ltx2_3A2V
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Ltx2_3A2V") Ltx2_3A2V("Ltx2_3A2V");
    }

}

