/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import market.femi.api.models.CharacterAlignment
import market.femi.api.models.WordAlignment

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param audio 
 * @param id 
 * @param lyrics 
 * @param characters 
 * @param credit 
 * @param loss 
 * @param userId 
 * @param words 
 */
@Serializable

data class LyricSync (

    @SerialName(value = "audio") @Required val audio: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.uuid.Uuid,

    @SerialName(value = "lyrics") @Required val lyrics: kotlin.String,

    @SerialName(value = "characters") val characters: kotlin.collections.List<CharacterAlignment>? = null,

    @SerialName(value = "credit") val credit: kotlin.Long? = null,

    @SerialName(value = "loss") val loss: kotlin.Double? = null,

    @SerialName(value = "user_id") val userId: kotlin.String? = null,

    @SerialName(value = "words") val words: kotlin.collections.List<WordAlignment>? = null

) {


}

