/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import market.femi.api.models.CharacterAlignment
import market.femi.api.models.WordAlignment

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param audio input image as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side
 * @param characters return
 * @param lyrics 
 * @param type 
 * @param words return
 */
@Serializable

data class LyricSync (

    /* input image as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side */
    @SerialName(value = "audio") @Required val audio: kotlin.String,

    /* return */
    @SerialName(value = "characters") @Required val characters: kotlin.collections.List<CharacterAlignment>,

    @SerialName(value = "lyrics") @Required val lyrics: kotlin.String,

    @SerialName(value = "type") @Required val type: LyricSync.Type,

    /* return */
    @SerialName(value = "words") @Required val words: kotlin.collections.List<WordAlignment>

) {

    /**
     * 
     *
     * Values: LyricSync
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "LyricSync") LyricSync("LyricSync");
    }

}

