/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import market.femi.api.models.AudioLine
import market.femi.api.models.Faq
import market.femi.api.models.Season

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param about 
 * @param audio 
 * @param audioLines 
 * @param faqs 
 * @param genre 
 * @param id 
 * @param playlist 
 * @param seasons 
 * @param summary 
 * @param userId 
 */
@Serializable

data class Project (

    @SerialName(value = "about") @Required val about: kotlin.String,

    @SerialName(value = "audio") @Required val audio: kotlin.String,

    @SerialName(value = "audio_lines") @Required val audioLines: kotlin.collections.List<AudioLine>,

    @SerialName(value = "faqs") @Required val faqs: kotlin.collections.List<Faq>,

    @SerialName(value = "genre") @Required val genre: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.uuid.Uuid,

    @SerialName(value = "playlist") @Required val playlist: kotlin.String,

    @SerialName(value = "seasons") @Required val seasons: kotlin.collections.List<Season>,

    @SerialName(value = "summary") @Required val summary: kotlin.String,

    @SerialName(value = "user_id") @Required val userId: kotlin.String

) {


}

