/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param draftImage 
 * @param finalImage 
 * @param id 
 */
@Serializable

data class Shot (

    @SerialName(value = "draft_image") @Required val draftImage: kotlin.String,

    @SerialName(value = "final_image") @Required val finalImage: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.uuid.Uuid

) {


}

