/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import market.femi.api.models.Status

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param amountCents 
 * @param id 
 * @param pubkey 
 * @param status 
 * @param userId 
 * @param credit 
 * @param loaded 
 * @param quotedOutUnits 
 * @param requestId 
 * @param signature 
 * @param signedTx 
 * @param unsignedTx 
 */
@Serializable

data class Solana (

    @SerialName(value = "amount_cents") @Required val amountCents: kotlin.Long,

    @SerialName(value = "id") @Required val id: kotlin.uuid.Uuid,

    @SerialName(value = "pubkey") @Required val pubkey: kotlin.String,

    @SerialName(value = "status") @Required val status: Status,

    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    @SerialName(value = "credit") val credit: kotlin.Long? = null,

    @SerialName(value = "loaded") val loaded: kotlin.Boolean? = null,

    @SerialName(value = "quoted_out_units") val quotedOutUnits: kotlin.Long? = null,

    @SerialName(value = "request_id") val requestId: kotlin.String? = null,

    @SerialName(value = "signature") val signature: kotlin.String? = null,

    @SerialName(value = "signed_tx") val signedTx: kotlin.String? = null,

    @SerialName(value = "unsigned_tx") val unsignedTx: kotlin.String? = null

) {


}

