/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param amountCents 
 * @param credit 
 * @param loaded 
 * @param paymentUrl 
 * @param stripePaymentIntentId 
 * @param stripeSessionId 
 * @param type 
 */
@Serializable

data class Stripe (

    @SerialName(value = "amount_cents") @Required val amountCents: kotlin.Long,

    @SerialName(value = "credit") @Required val credit: kotlin.Long,

    @SerialName(value = "loaded") @Required val loaded: kotlin.Boolean,

    @SerialName(value = "payment_url") @Required val paymentUrl: kotlin.String,

    @SerialName(value = "stripe_payment_intent_id") @Required val stripePaymentIntentId: kotlin.String,

    @SerialName(value = "stripe_session_id") @Required val stripeSessionId: kotlin.String,

    @SerialName(value = "type") @Required val type: Stripe.Type

) {

    /**
     * 
     *
     * Values: Stripe
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Stripe") Stripe("Stripe");
    }

}

