/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * default values
 *
 * @param credit 
 * @param file 
 * @param id uuid v7
 * @param userId 
 */
@Serializable

data class Upload (

    @SerialName(value = "credit") @Required val credit: kotlin.Long,

    @SerialName(value = "file") @Required val file: kotlin.String,

    /* uuid v7 */
    @SerialName(value = "id") @Required val id: kotlin.uuid.Uuid,

    @SerialName(value = "user_id") @Required val userId: kotlin.String

) {


}

