/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param end 
 * @param loss 
 * @param start 
 * @param text 
 */
@Serializable

data class WordAlignment (

    @SerialName(value = "end") @Required val end: kotlin.Double,

    @SerialName(value = "loss") @Required val loss: kotlin.Double,

    @SerialName(value = "start") @Required val start: kotlin.Double,

    @SerialName(value = "text") @Required val text: kotlin.String

) {


}

