/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.ApiPricing

class ApiPricingTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiPricing
        //val modelInstance = ApiPricing()

        // to test the property `artist`
        should("test artist") {
            // uncomment below to test the property
            //modelInstance.artist shouldBe ("TODO")
        }

        // to test the property `audio`
        should("test audio") {
            // uncomment below to test the property
            //modelInstance.audio shouldBe ("TODO")
        }

        // to test the property `chat`
        should("test chat") {
            // uncomment below to test the property
            //modelInstance.chat shouldBe ("TODO")
        }

        // to test the property `creator`
        should("test creator") {
            // uncomment below to test the property
            //modelInstance.creator shouldBe ("TODO")
        }

        // to test the property `director`
        should("test director") {
            // uncomment below to test the property
            //modelInstance.director shouldBe ("TODO")
        }

        // to test the property `falFlux2Pro`
        should("test falFlux2Pro") {
            // uncomment below to test the property
            //modelInstance.falFlux2Pro shouldBe ("TODO")
        }

        // to test the property `falNanoBanana2`
        should("test falNanoBanana2") {
            // uncomment below to test the property
            //modelInstance.falNanoBanana2 shouldBe ("TODO")
        }

        // to test the property `falZImageTurbo`
        should("test falZImageTurbo") {
            // uncomment below to test the property
            //modelInstance.falZImageTurbo shouldBe ("TODO")
        }

        // to test the property `gb`
        should("test gb") {
            // uncomment below to test the property
            //modelInstance.gb shouldBe ("TODO")
        }

        // to test the property `generate`
        should("test generate") {
            // uncomment below to test the property
            //modelInstance.generate shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `image`
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `lyricSync`
        should("test lyricSync") {
            // uncomment below to test the property
            //modelInstance.lyricSync shouldBe ("TODO")
        }

        // to test the property `microPixLyra`
        should("test microPixLyra") {
            // uncomment below to test the property
            //modelInstance.microPixLyra shouldBe ("TODO")
        }

        // to test the property `microPixVega`
        should("test microPixVega") {
            // uncomment below to test the property
            //modelInstance.microPixVega shouldBe ("TODO")
        }

        // to test the property `nanoPixLuna`
        should("test nanoPixLuna") {
            // uncomment below to test the property
            //modelInstance.nanoPixLuna shouldBe ("TODO")
        }

        // to test the property `nanoRenSpica`
        should("test nanoRenSpica") {
            // uncomment below to test the property
            //modelInstance.nanoRenSpica shouldBe ("TODO")
        }

        // to test the property `question`
        should("test question") {
            // uncomment below to test the property
            //modelInstance.question shouldBe ("TODO")
        }

        // to test the property `summary`
        should("test summary") {
            // uncomment below to test the property
            //modelInstance.summary shouldBe ("TODO")
        }

        // to test the property `upload`
        should("test upload") {
            // uncomment below to test the property
            //modelInstance.upload shouldBe ("TODO")
        }

    }
}
