/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.AudioLine

class AudioLineTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AudioLine
        //val modelInstance = AudioLine()

        // to test the property `context`
        should("test context") {
            // uncomment below to test the property
            //modelInstance.context shouldBe ("TODO")
        }

        // to test the property `goal`
        should("test goal") {
            // uncomment below to test the property
            //modelInstance.goal shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `line`
        should("test line") {
            // uncomment below to test the property
            //modelInstance.line shouldBe ("TODO")
        }

        // to test the property `startTime`
        should("test startTime") {
            // uncomment below to test the property
            //modelInstance.startTime shouldBe ("TODO")
        }

    }
}
