/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.Flux2DevI2I

class Flux2DevI2ITest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Flux2DevI2I
        //val modelInstance = Flux2DevI2I()

        // to test the property `comfyRequestId`
        should("test comfyRequestId") {
            // uncomment below to test the property
            //modelInstance.comfyRequestId shouldBe ("TODO")
        }

        // to test the property `file` - base64 return
        should("test file") {
            // uncomment below to test the property
            //modelInstance.file shouldBe ("TODO")
        }

        // to test the property `image` - input image as base64 — data URI (web) or raw base64 (android/ios); type detected server-side
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `prompt`
        should("test prompt") {
            // uncomment below to test the property
            //modelInstance.prompt shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
