/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.LyricSync
import market.femi.api.models.CharacterAlignment
import market.femi.api.models.WordAlignment

class LyricSyncTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LyricSync
        //val modelInstance = LyricSync()

        // to test the property `audio`
        should("test audio") {
            // uncomment below to test the property
            //modelInstance.audio shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `lyrics`
        should("test lyrics") {
            // uncomment below to test the property
            //modelInstance.lyrics shouldBe ("TODO")
        }

        // to test the property `characters`
        should("test characters") {
            // uncomment below to test the property
            //modelInstance.characters shouldBe ("TODO")
        }

        // to test the property `credit`
        should("test credit") {
            // uncomment below to test the property
            //modelInstance.credit shouldBe ("TODO")
        }

        // to test the property `loss`
        should("test loss") {
            // uncomment below to test the property
            //modelInstance.loss shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `words`
        should("test words") {
            // uncomment below to test the property
            //modelInstance.words shouldBe ("TODO")
        }

    }
}
