/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.Project
import market.femi.api.models.AudioLine
import market.femi.api.models.Faq
import market.femi.api.models.Season

class ProjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Project
        //val modelInstance = Project()

        // to test the property `about`
        should("test about") {
            // uncomment below to test the property
            //modelInstance.about shouldBe ("TODO")
        }

        // to test the property `audio`
        should("test audio") {
            // uncomment below to test the property
            //modelInstance.audio shouldBe ("TODO")
        }

        // to test the property `audioLines`
        should("test audioLines") {
            // uncomment below to test the property
            //modelInstance.audioLines shouldBe ("TODO")
        }

        // to test the property `faqs`
        should("test faqs") {
            // uncomment below to test the property
            //modelInstance.faqs shouldBe ("TODO")
        }

        // to test the property `genre`
        should("test genre") {
            // uncomment below to test the property
            //modelInstance.genre shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `playlist`
        should("test playlist") {
            // uncomment below to test the property
            //modelInstance.playlist shouldBe ("TODO")
        }

        // to test the property `seasons`
        should("test seasons") {
            // uncomment below to test the property
            //modelInstance.seasons shouldBe ("TODO")
        }

        // to test the property `summary`
        should("test summary") {
            // uncomment below to test the property
            //modelInstance.summary shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

    }
}
