/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.Shot

class ShotTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Shot
        //val modelInstance = Shot()

        // to test the property `draftImage`
        should("test draftImage") {
            // uncomment below to test the property
            //modelInstance.draftImage shouldBe ("TODO")
        }

        // to test the property `finalImage`
        should("test finalImage") {
            // uncomment below to test the property
            //modelInstance.finalImage shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
