/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.Solana
import market.femi.api.models.Status

class SolanaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Solana
        //val modelInstance = Solana()

        // to test the property `amountCents`
        should("test amountCents") {
            // uncomment below to test the property
            //modelInstance.amountCents shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `pubkey`
        should("test pubkey") {
            // uncomment below to test the property
            //modelInstance.pubkey shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `credit`
        should("test credit") {
            // uncomment below to test the property
            //modelInstance.credit shouldBe ("TODO")
        }

        // to test the property `loaded`
        should("test loaded") {
            // uncomment below to test the property
            //modelInstance.loaded shouldBe ("TODO")
        }

        // to test the property `quotedOutUnits`
        should("test quotedOutUnits") {
            // uncomment below to test the property
            //modelInstance.quotedOutUnits shouldBe ("TODO")
        }

        // to test the property `requestId`
        should("test requestId") {
            // uncomment below to test the property
            //modelInstance.requestId shouldBe ("TODO")
        }

        // to test the property `signature`
        should("test signature") {
            // uncomment below to test the property
            //modelInstance.signature shouldBe ("TODO")
        }

        // to test the property `signedTx`
        should("test signedTx") {
            // uncomment below to test the property
            //modelInstance.signedTx shouldBe ("TODO")
        }

        // to test the property `unsignedTx`
        should("test unsignedTx") {
            // uncomment below to test the property
            //modelInstance.unsignedTx shouldBe ("TODO")
        }

    }
}
