/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.Square
import market.femi.api.models.Status

class SquareTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Square
        //val modelInstance = Square()

        // to test the property `amountCents`
        should("test amountCents") {
            // uncomment below to test the property
            //modelInstance.amountCents shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `credit`
        should("test credit") {
            // uncomment below to test the property
            //modelInstance.credit shouldBe ("TODO")
        }

        // to test the property `loaded`
        should("test loaded") {
            // uncomment below to test the property
            //modelInstance.loaded shouldBe ("TODO")
        }

        // to test the property `paymentUrl`
        should("test paymentUrl") {
            // uncomment below to test the property
            //modelInstance.paymentUrl shouldBe ("TODO")
        }

        // to test the property `squareOrderId`
        should("test squareOrderId") {
            // uncomment below to test the property
            //modelInstance.squareOrderId shouldBe ("TODO")
        }

        // to test the property `squarePaymentId`
        should("test squarePaymentId") {
            // uncomment below to test the property
            //modelInstance.squarePaymentId shouldBe ("TODO")
        }

    }
}
