/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.Stripe

class StripeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Stripe
        //val modelInstance = Stripe()

        // to test the property `amountCents`
        should("test amountCents") {
            // uncomment below to test the property
            //modelInstance.amountCents shouldBe ("TODO")
        }

        // to test the property `credit`
        should("test credit") {
            // uncomment below to test the property
            //modelInstance.credit shouldBe ("TODO")
        }

        // to test the property `loaded`
        should("test loaded") {
            // uncomment below to test the property
            //modelInstance.loaded shouldBe ("TODO")
        }

        // to test the property `paymentUrl`
        should("test paymentUrl") {
            // uncomment below to test the property
            //modelInstance.paymentUrl shouldBe ("TODO")
        }

        // to test the property `stripePaymentIntentId`
        should("test stripePaymentIntentId") {
            // uncomment below to test the property
            //modelInstance.stripePaymentIntentId shouldBe ("TODO")
        }

        // to test the property `stripeSessionId`
        should("test stripeSessionId") {
            // uncomment below to test the property
            //modelInstance.stripeSessionId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
