/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.Wise
import market.femi.api.models.Status

class WiseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Wise
        //val modelInstance = Wise()

        // to test the property `amountCents`
        should("test amountCents") {
            // uncomment below to test the property
            //modelInstance.amountCents shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `reference`
        should("test reference") {
            // uncomment below to test the property
            //modelInstance.reference shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `credit`
        should("test credit") {
            // uncomment below to test the property
            //modelInstance.credit shouldBe ("TODO")
        }

        // to test the property `loaded`
        should("test loaded") {
            // uncomment below to test the property
            //modelInstance.loaded shouldBe ("TODO")
        }

        // to test the property `wiseCreditId`
        should("test wiseCreditId") {
            // uncomment below to test the property
            //modelInstance.wiseCreditId shouldBe ("TODO")
        }

    }
}
