/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.models.WordAlignment

class WordAlignmentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WordAlignment
        //val modelInstance = WordAlignment()

        // to test the property `end`
        should("test end") {
            // uncomment below to test the property
            //modelInstance.end shouldBe ("TODO")
        }

        // to test the property `loss`
        should("test loss") {
            // uncomment below to test the property
            //modelInstance.loss shouldBe ("TODO")
        }

        // to test the property `start`
        should("test start") {
            // uncomment below to test the property
            //modelInstance.start shouldBe ("TODO")
        }

        // to test the property `text`
        should("test text") {
            // uncomment below to test the property
            //modelInstance.text shouldBe ("TODO")
        }

    }
}
