/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.ApiApi
import market.femi.api.models.API

class ApiApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiApi
        //val apiInstance = ApiApi()

        // to test apiHandler
        should("test apiHandler") {
            // uncomment below to test apiHandler
            //val API : API =  // API | 
            //val result : API = apiInstance.apiHandler(API)
            //result shouldBe ("TODO")
        }

        // to test mediaGate
        should("test mediaGate") {
            // uncomment below to test mediaGate
            //val file : kotlin.String = file_example // kotlin.String | media filename in _upload
            //val result : kotlin.collections.List<kotlin.Int> = apiInstance.mediaGate(file)
            //result shouldBe ("TODO")
        }

    }
}
