/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.ApiHandlerApi
import market.femi.api.models.API

class ApiHandlerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiHandlerApi
        //val apiInstance = ApiHandlerApi()

        // to test apiHandler
        should("test apiHandler") {
            // uncomment below to test apiHandler
            //val API : API =  // API | 
            //val result : API = apiInstance.apiHandler(API)
            //result shouldBe ("TODO")
        }

    }
}
