/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.ApiKeyRouteApi
import market.femi.api.models.ApiKey

class ApiKeyRouteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiKeyRouteApi
        //val apiInstance = ApiKeyRouteApi()

        // to test apiKey
        should("test apiKey") {
            // uncomment below to test apiKey
            //val id : kotlin.uuid.Uuid = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.uuid.Uuid | 
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val key : kotlin.String = key_example // kotlin.String | 
            //val result : ApiKey = apiInstance.apiKey(id, userId, key)
            //result shouldBe ("TODO")
        }

    }
}
