/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.ApplePayRouteApi
import market.femi.api.models.ApplePay
import market.femi.api.models.ApplePayStatus

class ApplePayRouteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApplePayRouteApi
        //val apiInstance = ApplePayRouteApi()

        // to test applePay
        should("test applePay") {
            // uncomment below to test applePay
            //val credit : kotlin.Long = 789 // kotlin.Long | 
            //val currency : kotlin.String = currency_example // kotlin.String | 
            //val id : kotlin.uuid.Uuid = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.uuid.Uuid | uuid v7
            //val jws : kotlin.String = jws_example // kotlin.String | 
            //val loaded : kotlin.Boolean = true // kotlin.Boolean | 
            //val price : kotlin.Long = 789 // kotlin.Long | 
            //val productId : kotlin.String = productId_example // kotlin.String | 
            //val status : ApplePayStatus =  // ApplePayStatus | 
            //val transactionId : kotlin.String = transactionId_example // kotlin.String | 
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val result : ApplePay = apiInstance.applePay(credit, currency, id, jws, loaded, price, productId, status, transactionId, userId)
            //result shouldBe ("TODO")
        }

    }
}
