/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.LyricSyncRouteApi
import market.femi.api.models.CharacterAlignment
import market.femi.api.models.LyricSync
import market.femi.api.models.WordAlignment

class LyricSyncRouteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LyricSyncRouteApi
        //val apiInstance = LyricSyncRouteApi()

        // to test lyricSync
        should("test lyricSync") {
            // uncomment below to test lyricSync
            //val audio : kotlin.String = audio_example // kotlin.String | 
            //val id : kotlin.uuid.Uuid = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.uuid.Uuid | 
            //val lyrics : kotlin.String = lyrics_example // kotlin.String | 
            //val characters : kotlin.collections.List<CharacterAlignment> =  // kotlin.collections.List<CharacterAlignment> | 
            //val credit : kotlin.Long = 789 // kotlin.Long | 
            //val loss : kotlin.Double = 1.2 // kotlin.Double | 
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val words : kotlin.collections.List<WordAlignment> =  // kotlin.collections.List<WordAlignment> | 
            //val result : LyricSync = apiInstance.lyricSync(audio, id, lyrics, characters, credit, loss, userId, words)
            //result shouldBe ("TODO")
        }

    }
}
