/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.PayRouteApi
import market.femi.api.models.Pay
import market.femi.api.models.PayProvider
import market.femi.api.models.PayStatus

class PayRouteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayRouteApi
        //val apiInstance = PayRouteApi()

        // to test pay
        should("test pay") {
            // uncomment below to test pay
            //val id : kotlin.uuid.Uuid = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.uuid.Uuid | uuid v7
            //val provider : PayProvider =  // PayProvider | Selects the verification path: Apple App Store vs Google Play.
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val credit : kotlin.Long = 789 // kotlin.Long | 
            //val currency : kotlin.String = currency_example // kotlin.String | 
            //val jws : kotlin.String = jws_example // kotlin.String | Signed transaction JWS from StoreKit; the input to Apple verification.
            //val loaded : kotlin.Boolean = true // kotlin.Boolean | 
            //val orderId : kotlin.String = orderId_example // kotlin.String | Google's per-purchase `orderId`, returned by the Play Developer API (not the client). Not used for dedup — `ref_id` is — because promo-code purchases may have no `orderId`.
            //val packageName : kotlin.String = packageName_example // kotlin.String | 
            //val price : kotlin.Long = 789 // kotlin.Long | 
            //val productId : kotlin.String = productId_example // kotlin.String | 
            //val refId : kotlin.String = refId_example // kotlin.String | Globally-unique purchase id, used as the idempotency key for both stores. Apple: the `transactionId`, extracted server-side from the verified JWS   (empty on the incoming request — the server fills it in). Google: the `purchaseToken`, sent by the client. It is both the input to   Play Developer API verification and the idempotency key.
            //val status : PayStatus =  // PayStatus | 
            //val result : Pay = apiInstance.pay(id, provider, userId, credit, currency, jws, loaded, orderId, packageName, price, productId, refId, status)
            //result shouldBe ("TODO")
        }

    }
}
