/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.ProjectRouteApi
import market.femi.api.models.AudioLine
import market.femi.api.models.Faq
import market.femi.api.models.Project
import market.femi.api.models.Season

class ProjectRouteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProjectRouteApi
        //val apiInstance = ProjectRouteApi()

        // to test project
        should("test project") {
            // uncomment below to test project
            //val about : kotlin.String = about_example // kotlin.String | 
            //val audio : kotlin.String = audio_example // kotlin.String | 
            //val audioLines : kotlin.collections.List<AudioLine> =  // kotlin.collections.List<AudioLine> | 
            //val faqs : kotlin.collections.List<Faq> =  // kotlin.collections.List<Faq> | 
            //val genre : kotlin.String = genre_example // kotlin.String | 
            //val id : kotlin.uuid.Uuid = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.uuid.Uuid | 
            //val playlist : kotlin.String = playlist_example // kotlin.String | 
            //val seasons : kotlin.collections.List<Season> =  // kotlin.collections.List<Season> | 
            //val summary : kotlin.String = summary_example // kotlin.String | 
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val result : Project = apiInstance.project(about, audio, audioLines, faqs, genre, id, playlist, seasons, summary, userId)
            //result shouldBe ("TODO")
        }

    }
}
