/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.SolanaRouteApi
import market.femi.api.models.Solana
import market.femi.api.models.Status

class SolanaRouteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SolanaRouteApi
        //val apiInstance = SolanaRouteApi()

        // to test solana
        should("test solana") {
            // uncomment below to test solana
            //val amountCents : kotlin.Long = 789 // kotlin.Long | 
            //val id : kotlin.uuid.Uuid = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.uuid.Uuid | 
            //val pubkey : kotlin.String = pubkey_example // kotlin.String | 
            //val status : Status =  // Status | 
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val credit : kotlin.Long = 789 // kotlin.Long | 
            //val loaded : kotlin.Boolean = true // kotlin.Boolean | 
            //val quotedOutUnits : kotlin.Long = 789 // kotlin.Long | 
            //val requestId : kotlin.String = requestId_example // kotlin.String | 
            //val signature : kotlin.String = signature_example // kotlin.String | 
            //val signedTx : kotlin.String = signedTx_example // kotlin.String | 
            //val unsignedTx : kotlin.String = unsignedTx_example // kotlin.String | 
            //val result : Solana = apiInstance.solana(amountCents, id, pubkey, status, userId, credit, loaded, quotedOutUnits, requestId, signature, signedTx, unsignedTx)
            //result shouldBe ("TODO")
        }

    }
}
