/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.SquareRouteApi
import market.femi.api.models.Square
import market.femi.api.models.Status

class SquareRouteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SquareRouteApi
        //val apiInstance = SquareRouteApi()

        // to test square
        should("test square") {
            // uncomment below to test square
            //val amountCents : kotlin.Long = 789 // kotlin.Long | 
            //val id : kotlin.uuid.Uuid = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.uuid.Uuid | 
            //val status : Status =  // Status | 
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val credit : kotlin.Long = 789 // kotlin.Long | 
            //val loaded : kotlin.Boolean = true // kotlin.Boolean | 
            //val paymentUrl : kotlin.String = paymentUrl_example // kotlin.String | 
            //val squareOrderId : kotlin.String = squareOrderId_example // kotlin.String | 
            //val squarePaymentId : kotlin.String = squarePaymentId_example // kotlin.String | 
            //val result : Square = apiInstance.square(amountCents, id, status, userId, credit, loaded, paymentUrl, squareOrderId, squarePaymentId)
            //result shouldBe ("TODO")
        }

    }
}
