/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.UploadRouteApi
import market.femi.api.models.Upload

class UploadRouteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UploadRouteApi
        //val apiInstance = UploadRouteApi()

        // to test upload
        should("test upload") {
            // uncomment below to test upload
            //val credit : kotlin.Long = 789 // kotlin.Long | 
            //val file : kotlin.String = file_example // kotlin.String | 
            //val id : kotlin.uuid.Uuid = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.uuid.Uuid | uuid v7
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val result : Upload = apiInstance.upload(credit, file, id, userId)
            //result shouldBe ("TODO")
        }

    }
}
