/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import market.femi.api.apis.WiseRouteApi
import market.femi.api.models.Status
import market.femi.api.models.Wise

class WiseRouteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WiseRouteApi
        //val apiInstance = WiseRouteApi()

        // to test wise
        should("test wise") {
            // uncomment below to test wise
            //val amountCents : kotlin.Long = 789 // kotlin.Long | 
            //val currency : kotlin.String = currency_example // kotlin.String | 
            //val id : kotlin.uuid.Uuid = 38400000-8cf0-11bd-b23e-10b96e4ef00d // kotlin.uuid.Uuid | 
            //val reference : kotlin.String = reference_example // kotlin.String | 
            //val status : Status =  // Status | 
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val credit : kotlin.Long = 789 // kotlin.Long | 
            //val loaded : kotlin.Boolean = true // kotlin.Boolean | 
            //val wiseCreditId : kotlin.String = wiseCreditId_example // kotlin.String | 
            //val result : Wise = apiInstance.wise(amountCents, currency, id, reference, status, userId, credit, loaded, wiseCreditId)
            //result shouldBe ("TODO")
        }

    }
}
