/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import market.femi.api.models.API

import market.femi.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.FormBuilder
import io.ktor.client.request.forms.FormPart
import io.ktor.client.request.forms.InputProvider
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.encodeToJsonElement
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Recursively appends a value as bracket-keyed multipart form fields,
 * matching the wire format expected by serde_qs on the rust server.
 *
 * `files` is the per-call registry the caller passes on multipart operations
 * whose server-side `x-form-file-fields` vendor extension is non-empty. At
 * each JSON leaf the walker checks whether the leaf's *string value* is a
 * key in this map. If yes, it emits a streaming `FormPart` carrying the
 * matching `MultipartFileSource.provider` — bytes flow lazily through Ktor
 * during the upload. If no (or `files` is null), the leaf is appended as
 * plain text exactly as before, so non-file leaves and operations without a
 * registry are unaffected.
 *
 * Matching by leaf string value (typically a filename) lets nested file
 * leaves like `upsert[data][0][audio]` work without surfacing per-field
 * routing in the signature — the model field stays `String` (filename), the
 * caller hands in `mapOf("audio.mp3" to MultipartFileSource(...))`, and the
 * walker reconnects them at upload time.
 */
private inline fun <reified T : Any> FormBuilder.appendBracket(
    baseName: String,
    value: T,
    files: Map<String, MultipartFileSource>? = null,
) {
    appendBracketWalk(baseName, Json.Default.encodeToJsonElement(value), files)
}

private fun FormBuilder.appendBracketWalk(
    prefix: String,
    el: JsonElement,
    files: Map<String, MultipartFileSource>?,
) {
    when (el) {
        is JsonNull -> return
        is JsonPrimitive -> {
            val src = files?.get(el.content)
            if (src != null) {
                append(
                    FormPart(
                        prefix,
                        src.provider,
                        Headers.build {
                            append(
                                HttpHeaders.ContentDisposition,
                                "form-data; name=\"$prefix\"; filename=\"${src.filename}\"",
                            )
                            append(HttpHeaders.ContentType, src.contentType.toString())
                        },
                    ),
                )
            } else {
                append(prefix, el.content)
            }
        }
        is JsonArray -> el.forEachIndexed { i, v -> appendBracketWalk("$prefix[$i]", v, files) }
        is JsonObject -> el.forEach { (k, v) -> appendBracketWalk("$prefix[$k]", v, files) }
    }
}

open class ApiApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * 
     * @param API 
     * @return API
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun apiHandler(API: API): HttpResponse<API> {

        val localVariableAuthNames = listOf<String>("bearer")

        val localVariableBody = API

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Auth + per-GB debit gate in front of the &#x60;_upload&#x60; ServeDir on femi.market.   - not a media file → pass through (static site, app data, 404), free   - media file that isn&#39;t a real file in &#x60;_upload&#x60; → pass through, free   - media file in &#x60;_upload&#x60; → require Bearer, charge &#x60;size × pricing.gb&#x60;,     record a debit in the astc ledger, then let ServeDir stream the bytes. The gate only authorizes/charges; ServeDir still does the actual file streaming (range requests, mime, etc.).
     * &#x60;#[utoipa::path]&#x60; here is doc-only — the fn runs as &#x60;from_fn&#x60; middleware, not a route handler, but the attribute still emits the spec entry so the generated clients get a typed &#x60;downloadMedia(file)&#x60;. &#x60;servers(...)&#x60; pins it to femi.market (the global server is api.earnfemi.com); &#x60;Request&#x60;/&#x60;Next&#x60; args aren&#39;t documentable extractors so utoipa ignores them and uses the explicit &#x60;params&#x60;.
     * @param file media filename in _upload
     * @return kotlin.collections.List<kotlin.Int>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun mediaGate(file: kotlin.String): HttpResponse<kotlin.collections.List<kotlin.Int>> {

        val localVariableAuthNames = listOf<String>("bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/{file}".replace("{" + "file" + "}", "$file"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<MediaGateResponse>().map { value }
    }

    @Serializable(MediaGateResponse.Companion::class)
    private class MediaGateResponse(val value: List<kotlin.Int>) {
        companion object : KSerializer<MediaGateResponse> {
            private val serializer: KSerializer<List<kotlin.Int>> = serializer<List<kotlin.Int>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: MediaGateResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = MediaGateResponse(serializer.deserialize(decoder))
        }
    }

}
