/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import market.femi.api.models.Pay
import market.femi.api.models.PayProvider
import market.femi.api.models.PayStatus

import market.femi.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.FormBuilder
import io.ktor.client.request.forms.FormPart
import io.ktor.client.request.forms.InputProvider
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.encodeToJsonElement
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Recursively appends a value as bracket-keyed multipart form fields,
 * matching the wire format expected by serde_qs on the rust server.
 *
 * `files` is the per-call registry the caller passes on multipart operations
 * whose server-side `x-form-file-fields` vendor extension is non-empty. At
 * each JSON leaf the walker checks whether the leaf's *string value* is a
 * key in this map. If yes, it emits a streaming `FormPart` carrying the
 * matching `MultipartFileSource.provider` — bytes flow lazily through Ktor
 * during the upload. If no (or `files` is null), the leaf is appended as
 * plain text exactly as before, so non-file leaves and operations without a
 * registry are unaffected.
 *
 * Matching by leaf string value (typically a filename) lets nested file
 * leaves like `upsert[data][0][audio]` work without surfacing per-field
 * routing in the signature — the model field stays `String` (filename), the
 * caller hands in `mapOf("audio.mp3" to MultipartFileSource(...))`, and the
 * walker reconnects them at upload time.
 */
private inline fun <reified T : Any> FormBuilder.appendBracket(
    baseName: String,
    value: T,
    files: Map<String, MultipartFileSource>? = null,
) {
    appendBracketWalk(baseName, Json.Default.encodeToJsonElement(value), files)
}

private fun FormBuilder.appendBracketWalk(
    prefix: String,
    el: JsonElement,
    files: Map<String, MultipartFileSource>?,
) {
    when (el) {
        is JsonNull -> return
        is JsonPrimitive -> {
            val src = files?.get(el.content)
            if (src != null) {
                append(
                    FormPart(
                        prefix,
                        src.provider,
                        Headers.build {
                            append(
                                HttpHeaders.ContentDisposition,
                                "form-data; name=\"$prefix\"; filename=\"${src.filename}\"",
                            )
                            append(HttpHeaders.ContentType, src.contentType.toString())
                        },
                    ),
                )
            } else {
                append(prefix, el.content)
            }
        }
        is JsonArray -> el.forEachIndexed { i, v -> appendBracketWalk("$prefix[$i]", v, files) }
        is JsonObject -> el.forEach { (k, v) -> appendBracketWalk("$prefix[$k]", v, files) }
    }
}

open class PayRouteApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * 
     * @param id uuid v7
     * @param provider Selects the verification path: Apple App Store vs Google Play.
     * @param userId 
     * @param credit  (optional)
     * @param currency  (optional)
     * @param jws Signed transaction JWS from StoreKit; the input to Apple verification. (optional)
     * @param loaded  (optional)
     * @param orderId Google&#39;s per-purchase &#x60;orderId&#x60;, returned by the Play Developer API (not the client). Not used for dedup — &#x60;ref_id&#x60; is — because promo-code purchases may have no &#x60;orderId&#x60;. (optional)
     * @param packageName  (optional)
     * @param price  (optional)
     * @param productId  (optional)
     * @param refId Globally-unique purchase id, used as the idempotency key for both stores. Apple: the &#x60;transactionId&#x60;, extracted server-side from the verified JWS   (empty on the incoming request — the server fills it in). Google: the &#x60;purchaseToken&#x60;, sent by the client. It is both the input to   Play Developer API verification and the idempotency key. (optional)
     * @param status  (optional)
     * @return Pay
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun pay(id: kotlin.uuid.Uuid, provider: PayProvider, userId: kotlin.String, credit: kotlin.Long? = null, currency: kotlin.String? = null, jws: kotlin.String? = null, loaded: kotlin.Boolean? = null, orderId: kotlin.String? = null, packageName: kotlin.String? = null, price: kotlin.Long? = null, productId: kotlin.String? = null, refId: kotlin.String? = null, status: PayStatus? = null, files: Map<String, MultipartFileSource>? = null): HttpResponse<Pay> {

        val localVariableAuthNames = listOf<String>("bearer")

        val localVariableBody = 
            formData {
                credit?.let { appendBracket("credit", it, files) }
                currency?.let { appendBracket("currency", it, files) }
                id?.let { appendBracket("id", it, files) }
                jws?.let { appendBracket("jws", it, files) }
                loaded?.let { appendBracket("loaded", it, files) }
                orderId?.let { appendBracket("order_id", it, files) }
                packageName?.let { appendBracket("package_name", it, files) }
                price?.let { appendBracket("price", it, files) }
                productId?.let { appendBracket("product_id", it, files) }
                provider?.let { appendBracket("provider", it, files) }
                refId?.let { appendBracket("ref_id", it, files) }
                status?.let { appendBracket("status", it, files) }
                userId?.let { appendBracket("user_id", it, files) }
            }

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/pay",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return multipartFormRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
