/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package market.femi.api.apis

import market.femi.api.models.AudioLine
import market.femi.api.models.Faq
import market.femi.api.models.Project
import market.femi.api.models.Season

import market.femi.api.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.FormBuilder
import io.ktor.client.request.forms.FormPart
import io.ktor.client.request.forms.InputProvider
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.encodeToJsonElement
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Recursively appends a value as bracket-keyed multipart form fields,
 * matching the wire format expected by serde_qs on the rust server.
 *
 * `files` is the per-call registry the caller passes on multipart operations
 * whose server-side `x-form-file-fields` vendor extension is non-empty. At
 * each JSON leaf the walker checks whether the leaf's *string value* is a
 * key in this map. If yes, it emits a streaming `FormPart` carrying the
 * matching `MultipartFileSource.provider` — bytes flow lazily through Ktor
 * during the upload. If no (or `files` is null), the leaf is appended as
 * plain text exactly as before, so non-file leaves and operations without a
 * registry are unaffected.
 *
 * Matching by leaf string value (typically a filename) lets nested file
 * leaves like `upsert[data][0][audio]` work without surfacing per-field
 * routing in the signature — the model field stays `String` (filename), the
 * caller hands in `mapOf("audio.mp3" to MultipartFileSource(...))`, and the
 * walker reconnects them at upload time.
 */
private inline fun <reified T : Any> FormBuilder.appendBracket(
    baseName: String,
    value: T,
    files: Map<String, MultipartFileSource>? = null,
) {
    appendBracketWalk(baseName, Json.Default.encodeToJsonElement(value), files)
}

private fun FormBuilder.appendBracketWalk(
    prefix: String,
    el: JsonElement,
    files: Map<String, MultipartFileSource>?,
) {
    when (el) {
        is JsonNull -> return
        is JsonPrimitive -> {
            val src = files?.get(el.content)
            if (src != null) {
                append(
                    FormPart(
                        prefix,
                        src.provider,
                        Headers.build {
                            append(
                                HttpHeaders.ContentDisposition,
                                "form-data; name=\"$prefix\"; filename=\"${src.filename}\"",
                            )
                            append(HttpHeaders.ContentType, src.contentType.toString())
                        },
                    ),
                )
            } else {
                append(prefix, el.content)
            }
        }
        is JsonArray -> el.forEachIndexed { i, v -> appendBracketWalk("$prefix[$i]", v, files) }
        is JsonObject -> el.forEach { (k, v) -> appendBracketWalk("$prefix[$k]", v, files) }
    }
}

open class ProjectRouteApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * 
     * 
     * @param about 
     * @param audio 
     * @param audioLines 
     * @param faqs 
     * @param genre 
     * @param id 
     * @param playlist 
     * @param seasons 
     * @param summary 
     * @param userId 
     * @return Project
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun project(about: kotlin.String, audio: kotlin.String, audioLines: kotlin.collections.List<AudioLine>, faqs: kotlin.collections.List<Faq>, genre: kotlin.String, id: kotlin.uuid.Uuid, playlist: kotlin.String, seasons: kotlin.collections.List<Season>, summary: kotlin.String, userId: kotlin.String, files: Map<String, MultipartFileSource>? = null): HttpResponse<Project> {

        val localVariableAuthNames = listOf<String>("bearer")

        val localVariableBody = 
            formData {
                about?.let { appendBracket("about", it, files) }
                audio?.let { appendBracket("audio", it, files) }
                audioLines?.let { appendBracket("audio_lines", it, files) }
                faqs?.let { appendBracket("faqs", it, files) }
                genre?.let { appendBracket("genre", it, files) }
                id?.let { appendBracket("id", it, files) }
                playlist?.let { appendBracket("playlist", it, files) }
                seasons?.let { appendBracket("seasons", it, files) }
                summary?.let { appendBracket("summary", it, files) }
                userId?.let { appendBracket("user_id", it, files) }
            }

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/project",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return multipartFormRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
